### ISSUE TITLE
Issues with words

### ISSUE THREAD

**Issue by Montandalar** [C-C-Minetest-Server/cottages#2]
There are a few terms that seem wrong to me in the text of the mod:
- Reet instead of reed - this is only listed in Wiktionary as a German word, not English, and the German is a variant of "Ried". It's also made of papyrus reeds, not "reets". Reet is also a Geordie way of saying "right", but that's not a related word.
- "Red" roof instead of "terracotta". It's not really red in colouration. Terracotta is a recognised termin English for a kind of pottery.
- "Black" roof instead of "asphalt" - yes, asphalt roofing is real, it's not a material only for roads.
- "Brown" roof instead of "brown shingle". Less descriptive like the last two I mentioned.

There is also a German locale file but it just doesn't work with the game set to German, everything in the mod is still in English.

**Comment by Emojigit** [comment]
The German translation is not working now because I changed the wording a lot. I kept the translations from upstream just for the translator's convenience.
